from functions import get_connection

conn, cursor = get_connection()
cursor.execute("""ALTER TABLE route_daily_delays
    ADD COLUMN above_1_minute SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN above_2_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN above_5_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN above_10_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN above_15_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN above_30_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN before_1_minute SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN before_2_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN before_5_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN before_10_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN total_cancelled SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN total_trips SMALLINT UNSIGNED NOT NULL DEFAULT 0
""")